'use client'

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Locale = 'en' | 'fr' | 'ar'

interface LanguageContextType {
  locale: Locale
  setLocale: (locale: Locale) => void
  t: (key: string) => string
  isRTL: boolean
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation messages
const messages = {
  en: {
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.refresh': 'Refresh',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.move': 'Move',
    'common.rename': 'Rename',
    'common.view': 'View',
    'common.select': 'Select',
    'common.selectAll': 'Select All',
    'common.clear': 'Clear',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.date': 'Date',
    'common.size': 'Size',
    'common.type': 'Type',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.settings': 'Settings',
    'common.profile': 'Profile',
    'common.logout': 'Logout',
    'common.login': 'Login',
    'common.signIn': 'Sign In',
    'common.signOut': 'Sign Out',
    'common.welcome': 'Welcome',
    'common.home': 'Home',
    'common.dashboard': 'Dashboard',
    'common.administration': 'Administration',
    'common.users': 'Users',
    'common.roles': 'Roles',
    'common.groups': 'Groups',
    'common.permissions': 'Permissions',
    'common.documents': 'Documents',
    'common.folders': 'Folders',
    'common.favorites': 'Favorites',
    'common.trash': 'Trash',
    'common.models': 'Models',
    'common.searchResults': 'Search Results',
    'common.noResults': 'No results found',
    'common.noData': 'No data available',
    'common.itemsPerPage': 'Items per page',
    'common.page': 'Page',
    'common.of': 'of',
    'common.total': 'Total',
    'common.showing': 'Showing',
    'common.to': 'to',
    'common.entries': 'entries',
    'navigation.language': 'Language',
    'common.recent': 'Recent',
    'common.tags': 'Tags',
    'common.allFiles': 'All Files',
    'common.myFolders': 'My Folders',
    'common.documentModels': 'Document Models',
    'admin.users': 'Users',
    'admin.roles': 'Roles',
    'admin.groups': 'Groups',
    'admin.assignRoles': 'Assign Roles',
    'admin.user': 'User',
    'admin.email': 'Email',
    'admin.created': 'Created',
    'admin.actions': 'Actions',
    'admin.assignedRoles': 'Assigned Roles',
    'admin.groupMemberships': 'Group Memberships',
    'admin.description': 'Description',
    'admin.permissions': 'Permissions',
    'admin.members': 'Members',
    'admin.userManagement': 'User Management',
    'admin.manageUsersRolesGroups': 'Manage users, roles, and groups with Keycloak-like permissions',
    'dashboard.welcome': 'Welcome back, Admin!',
    'dashboard.whatsHappening': 'Here\'s what\'s happening with your documents today.',
    'dashboard.totalDocuments': 'Total Documents',
    'dashboard.teamMembers': 'Team Members',
    'dashboard.downloads': 'Downloads',
    'dashboard.recentDocuments': 'Recent Documents',
    'dashboard.noRecentDocuments': 'Recent documents will appear here. Start by uploading your first document!',
    'dashboard.fromLastMonth': 'from last month',
    'trash.title': 'Trash',
    'trash.deletedItems': 'deleted items',
    'trash.emptyTrash': 'Empty Trash',
    'trash.restoreAll': 'Restore All',
    'trash.noItems': 'No items in trash',
    'trash.noItemsDescription': 'Deleted items will appear here and can be restored within 30 days',
    'trash.deletedBy': 'Deleted by',
    'trash.deletedAt': 'Deleted at',
    'trash.originalPath': 'Original path',
    'trash.restore': 'Restore',
    'trash.deletePermanently': 'Delete Permanently',
    'models.title': 'Document Models',
    'models.manageModels': 'Manage document models and metadata definitions',
    'models.createModel': 'Create Model',
    'models.modelName': 'Model Name',
    'models.description': 'Description',
    'models.metadataDefinitions': 'Metadata Definitions',
    'models.addDefinition': 'Add Definition',
    'models.key': 'Key',
    'models.dataType': 'Data Type',
    'models.mandatory': 'Mandatory',
    'models.options': 'Options',
    'models.noModels': 'No models found',
    'models.createFirstModel': 'Create your first document model to get started',
    'folders.title': 'Folders',
    'folders.manageFolders': 'Manage your document folders and organization',
    'folders.createFolder': 'Create Folder',
    'folders.folderName': 'Folder Name',
    'folders.parentFolder': 'Parent Folder',
    'folders.public': 'Public',
    'folders.private': 'Private',
    'folders.createdBy': 'Created by',
    'folders.createdAt': 'Created at',
    'folders.size': 'Size',
    'folders.noFolders': 'No folders found',
    'folders.createFirstFolder': 'Create your first folder to organize your documents',
    'documents.title': 'Document Details',
    'documents.download': 'Download',
    'documents.share': 'Share',
    'documents.edit': 'Edit',
    'documents.delete': 'Delete',
    'documents.view': 'View',
    'documents.version': 'Version',
    'documents.ownedBy': 'Owned by',
    'documents.size': 'Size',
    'documents.type': 'Type',
    'documents.createdAt': 'Created at',
    'documents.updatedAt': 'Updated at',
    'documents.metadata': 'Metadata',
    'documents.versions': 'Versions',
    'documents.comments': 'Comments',
    'documents.addComment': 'Add Comment',
    'documents.noComments': 'No comments yet',
    'documents.addFirstComment': 'Be the first to add a comment'
  },
  fr: {
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.create': 'Créer',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.refresh': 'Actualiser',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.close': 'Fermer',
    'common.open': 'Ouvrir',
    'common.upload': 'Télécharger',
    'common.download': 'Télécharger',
    'common.share': 'Partager',
    'common.copy': 'Copier',
    'common.move': 'Déplacer',
    'common.rename': 'Renommer',
    'common.view': 'Voir',
    'common.select': 'Sélectionner',
    'common.selectAll': 'Tout sélectionner',
    'common.clear': 'Effacer',
    'common.confirm': 'Confirmer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.ok': 'OK',
    'common.name': 'Nom',
    'common.description': 'Description',
    'common.date': 'Date',
    'common.size': 'Taille',
    'common.type': 'Type',
    'common.status': 'Statut',
    'common.actions': 'Actions',
    'common.settings': 'Paramètres',
    'common.profile': 'Profil',
    'common.logout': 'Déconnexion',
    'common.login': 'Connexion',
    'common.signIn': 'Se connecter',
    'common.signOut': 'Se déconnecter',
    'common.welcome': 'Bienvenue',
    'common.home': 'Accueil',
    'common.dashboard': 'Tableau de bord',
    'common.administration': 'Administration',
    'common.users': 'Utilisateurs',
    'common.roles': 'Rôles',
    'common.groups': 'Groupes',
    'common.permissions': 'Permissions',
    'common.documents': 'Documents',
    'common.folders': 'Dossiers',
    'common.favorites': 'Favoris',
    'common.trash': 'Corbeille',
    'common.models': 'Modèles',
    'common.searchResults': 'Résultats de recherche',
    'common.noResults': 'Aucun résultat trouvé',
    'common.noData': 'Aucune donnée disponible',
    'common.itemsPerPage': 'Éléments par page',
    'common.page': 'Page',
    'common.of': 'de',
    'common.total': 'Total',
    'common.showing': 'Affichage',
    'common.to': 'à',
    'common.entries': 'entrées',
    'navigation.language': 'Langue',
    'common.recent': 'Récent',
    'common.tags': 'Étiquettes',
    'common.allFiles': 'Tous les fichiers',
    'common.myFolders': 'Mes dossiers',
    'common.documentModels': 'Modèles de documents',
    'admin.users': 'Utilisateurs',
    'admin.roles': 'Rôles',
    'admin.groups': 'Groupes',
    'admin.assignRoles': 'Assigner des rôles',
    'admin.user': 'Utilisateur',
    'admin.email': 'E-mail',
    'admin.created': 'Créé',
    'admin.actions': 'Actions',
    'admin.assignedRoles': 'Rôles assignés',
    'admin.groupMemberships': 'Appartenances aux groupes',
    'admin.description': 'Description',
    'admin.permissions': 'Permissions',
    'admin.members': 'Membres',
    'admin.userManagement': 'Gestion des utilisateurs',
    'admin.manageUsersRolesGroups': 'Gérer les utilisateurs, rôles et groupes avec des permissions de type Keycloak',
    'dashboard.welcome': 'Bon retour, Admin !',
    'dashboard.whatsHappening': 'Voici ce qui se passe avec vos documents aujourd\'hui.',
    'dashboard.totalDocuments': 'Total des Documents',
    'dashboard.teamMembers': 'Membres de l\'Équipe',
    'dashboard.downloads': 'Téléchargements',
    'dashboard.recentDocuments': 'Documents Récents',
    'dashboard.noRecentDocuments': 'Les documents récents apparaîtront ici. Commencez par télécharger votre premier document !',
    'dashboard.fromLastMonth': 'du mois dernier',
    'trash.title': 'Corbeille',
    'trash.deletedItems': 'éléments supprimés',
    'trash.emptyTrash': 'Vider la Corbeille',
    'trash.restoreAll': 'Tout Restaurer',
    'trash.noItems': 'Aucun élément dans la corbeille',
    'trash.noItemsDescription': 'Les éléments supprimés apparaîtront ici et peuvent être restaurés dans les 30 jours',
    'trash.deletedBy': 'Supprimé par',
    'trash.deletedAt': 'Supprimé le',
    'trash.originalPath': 'Chemin d\'origine',
    'trash.restore': 'Restaurer',
    'trash.deletePermanently': 'Supprimer Définitivement',
    'models.title': 'Modèles de Documents',
    'models.manageModels': 'Gérer les modèles de documents et les définitions de métadonnées',
    'models.createModel': 'Créer un Modèle',
    'models.modelName': 'Nom du Modèle',
    'models.description': 'Description',
    'models.metadataDefinitions': 'Définitions de Métadonnées',
    'models.addDefinition': 'Ajouter une Définition',
    'models.key': 'Clé',
    'models.dataType': 'Type de Données',
    'models.mandatory': 'Obligatoire',
    'models.options': 'Options',
    'models.noModels': 'Aucun modèle trouvé',
    'models.createFirstModel': 'Créez votre premier modèle de document pour commencer',
    'folders.title': 'Dossiers',
    'folders.manageFolders': 'Gérer vos dossiers de documents et l\'organisation',
    'folders.createFolder': 'Créer un Dossier',
    'folders.folderName': 'Nom du Dossier',
    'folders.parentFolder': 'Dossier Parent',
    'folders.public': 'Public',
    'folders.private': 'Privé',
    'folders.createdBy': 'Créé par',
    'folders.createdAt': 'Créé le',
    'folders.size': 'Taille',
    'folders.noFolders': 'Aucun dossier trouvé',
    'folders.createFirstFolder': 'Créez votre premier dossier pour organiser vos documents',
    'documents.title': 'Détails du Document',
    'documents.download': 'Télécharger',
    'documents.share': 'Partager',
    'documents.edit': 'Modifier',
    'documents.delete': 'Supprimer',
    'documents.view': 'Voir',
    'documents.version': 'Version',
    'documents.ownedBy': 'Propriétaire',
    'documents.size': 'Taille',
    'documents.type': 'Type',
    'documents.createdAt': 'Créé le',
    'documents.updatedAt': 'Mis à jour le',
    'documents.metadata': 'Métadonnées',
    'documents.versions': 'Versions',
    'documents.comments': 'Commentaires',
    'documents.addComment': 'Ajouter un Commentaire',
    'documents.noComments': 'Aucun commentaire pour le moment',
    'documents.addFirstComment': 'Soyez le premier à ajouter un commentaire'
  },
  ar: {
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.create': 'إنشاء',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.refresh': 'تحديث',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.close': 'إغلاق',
    'common.open': 'فتح',
    'common.upload': 'رفع',
    'common.download': 'تحميل',
    'common.share': 'مشاركة',
    'common.copy': 'نسخ',
    'common.move': 'نقل',
    'common.rename': 'إعادة تسمية',
    'common.view': 'عرض',
    'common.select': 'اختيار',
    'common.selectAll': 'اختيار الكل',
    'common.clear': 'مسح',
    'common.confirm': 'تأكيد',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.ok': 'موافق',
    'common.name': 'الاسم',
    'common.description': 'الوصف',
    'common.date': 'التاريخ',
    'common.size': 'الحجم',
    'common.type': 'النوع',
    'common.status': 'الحالة',
    'common.actions': 'الإجراءات',
    'common.settings': 'الإعدادات',
    'common.profile': 'الملف الشخصي',
    'common.logout': 'تسجيل الخروج',
    'common.login': 'تسجيل الدخول',
    'common.signIn': 'تسجيل الدخول',
    'common.signOut': 'تسجيل الخروج',
    'common.welcome': 'مرحباً',
    'common.home': 'الرئيسية',
    'common.dashboard': 'لوحة التحكم',
    'common.administration': 'الإدارة',
    'common.users': 'المستخدمون',
    'common.roles': 'الأدوار',
    'common.groups': 'المجموعات',
    'common.permissions': 'الصلاحيات',
    'common.documents': 'المستندات',
    'common.folders': 'المجلدات',
    'common.favorites': 'المفضلة',
    'common.trash': 'المهملات',
    'common.models': 'النماذج',
    'common.searchResults': 'نتائج البحث',
    'common.noResults': 'لا توجد نتائج',
    'common.noData': 'لا توجد بيانات متاحة',
    'common.itemsPerPage': 'عناصر في الصفحة',
    'common.page': 'صفحة',
    'common.of': 'من',
    'common.total': 'المجموع',
    'common.showing': 'عرض',
    'common.to': 'إلى',
    'common.entries': 'إدخالات',
    'navigation.language': 'اللغة',
    'common.recent': 'حديث',
    'common.tags': 'العلامات',
    'common.allFiles': 'جميع الملفات',
    'common.myFolders': 'مجلداتي',
    'common.documentModels': 'نماذج المستندات',
    'admin.users': 'المستخدمون',
    'admin.roles': 'الأدوار',
    'admin.groups': 'المجموعات',
    'admin.assignRoles': 'تعيين الأدوار',
    'admin.user': 'المستخدم',
    'admin.email': 'البريد الإلكتروني',
    'admin.created': 'تاريخ الإنشاء',
    'admin.actions': 'الإجراءات',
    'admin.assignedRoles': 'الأدوار المعينة',
    'admin.groupMemberships': 'عضوية المجموعات',
    'admin.description': 'الوصف',
    'admin.permissions': 'الصلاحيات',
    'admin.members': 'الأعضاء',
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.manageUsersRolesGroups': 'إدارة المستخدمين والأدوار والمجموعات مع صلاحيات مشابهة لـ Keycloak',
    'dashboard.welcome': 'مرحباً بعودتك، المدير!',
    'dashboard.whatsHappening': 'إليك ما يحدث مع مستنداتك اليوم.',
    'dashboard.totalDocuments': 'إجمالي المستندات',
    'dashboard.teamMembers': 'أعضاء الفريق',
    'dashboard.downloads': 'التحميلات',
    'dashboard.recentDocuments': 'المستندات الحديثة',
    'dashboard.noRecentDocuments': 'ستظهر المستندات الحديثة هنا. ابدأ برفع أول مستند لك!',
    'dashboard.fromLastMonth': 'من الشهر الماضي',
    'trash.title': 'المهملات',
    'trash.deletedItems': 'عناصر محذوفة',
    'trash.emptyTrash': 'إفراغ المهملات',
    'trash.restoreAll': 'استعادة الكل',
    'trash.noItems': 'لا توجد عناصر في المهملات',
    'trash.noItemsDescription': 'ستظهر العناصر المحذوفة هنا ويمكن استعادتها خلال 30 يوماً',
    'trash.deletedBy': 'حذف بواسطة',
    'trash.deletedAt': 'تاريخ الحذف',
    'trash.originalPath': 'المسار الأصلي',
    'trash.restore': 'استعادة',
    'trash.deletePermanently': 'حذف نهائي',
    'models.title': 'نماذج المستندات',
    'models.manageModels': 'إدارة نماذج المستندات وتعريفات البيانات الوصفية',
    'models.createModel': 'إنشاء نموذج',
    'models.modelName': 'اسم النموذج',
    'models.description': 'الوصف',
    'models.metadataDefinitions': 'تعريفات البيانات الوصفية',
    'models.addDefinition': 'إضافة تعريف',
    'models.key': 'المفتاح',
    'models.dataType': 'نوع البيانات',
    'models.mandatory': 'إجباري',
    'models.options': 'الخيارات',
    'models.noModels': 'لم يتم العثور على نماذج',
    'models.createFirstModel': 'أنشئ أول نموذج مستند للبدء',
    'folders.title': 'المجلدات',
    'folders.manageFolders': 'إدارة مجلدات المستندات والتنظيم',
    'folders.createFolder': 'إنشاء مجلد',
    'folders.folderName': 'اسم المجلد',
    'folders.parentFolder': 'المجلد الأب',
    'folders.public': 'عام',
    'folders.private': 'خاص',
    'folders.createdBy': 'أنشئ بواسطة',
    'folders.createdAt': 'تاريخ الإنشاء',
    'folders.size': 'الحجم',
    'folders.noFolders': 'لم يتم العثور على مجلدات',
    'folders.createFirstFolder': 'أنشئ أول مجلد لتنظيم مستنداتك',
    'documents.title': 'تفاصيل المستند',
    'documents.download': 'تحميل',
    'documents.share': 'مشاركة',
    'documents.edit': 'تعديل',
    'documents.delete': 'حذف',
    'documents.view': 'عرض',
    'documents.version': 'الإصدار',
    'documents.ownedBy': 'المالك',
    'documents.size': 'الحجم',
    'documents.type': 'النوع',
    'documents.createdAt': 'تاريخ الإنشاء',
    'documents.updatedAt': 'تاريخ التحديث',
    'documents.metadata': 'البيانات الوصفية',
    'documents.versions': 'الإصدارات',
    'documents.comments': 'التعليقات',
    'documents.addComment': 'إضافة تعليق',
    'documents.noComments': 'لا توجد تعليقات بعد',
    'documents.addFirstComment': 'كن أول من يضيف تعليقاً'
  }
}

interface LanguageProviderProps {
  children: ReactNode
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [locale, setLocale] = useState<Locale>('en')

  // Load saved locale from localStorage on mount
  useEffect(() => {
    const savedLocale = localStorage.getItem('locale') as Locale
    if (savedLocale && ['en', 'fr', 'ar'].includes(savedLocale)) {
      setLocale(savedLocale)
    }
  }, [])

  // Save locale to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('locale', locale)
    
    // Update HTML dir attribute for RTL support
    if (locale === 'ar') {
      document.documentElement.setAttribute('dir', 'rtl')
      document.documentElement.setAttribute('lang', 'ar')
    } else {
      document.documentElement.setAttribute('dir', 'ltr')
      document.documentElement.setAttribute('lang', locale)
    }
  }, [locale])

  const t = (key: string): string => {
    return messages[locale][key as keyof typeof messages[typeof locale]] || key
  }

  const isRTL = locale === 'ar'

  const value: LanguageContextType = {
    locale,
    setLocale,
    t,
    isRTL
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
