/**
 * Mock data for Email Management module
 * Comprehensive mock data for Email Campaigns feature
 */

import type {
  EmailCampaign,
  EmailCampaignStatus,
  EmailCampaignType,
  TargetType,
  CampaignActivity,
  MockUser,
  MockRole,
  MockTemplate,
  EmailTemplate,
  EmailLog,
  EmailStats
} from './types';

// ============================================================================
// Mock Users for Recipient Selection
// ============================================================================

export const mockUsers: MockUser[] = [
  { id: 'u1', name: 'John Smith', email: 'john.smith@company.com' },
  { id: 'u2', name: 'Sarah Johnson', email: 'sarah.johnson@company.com' },
  { id: 'u3', name: 'Michael Brown', email: 'michael.brown@company.com' },
  { id: 'u4', name: 'Emily Davis', email: 'emily.davis@company.com' },
  { id: 'u5', name: 'Robert Wilson', email: 'robert.wilson@company.com' },
  { id: 'u6', name: 'Jennifer Taylor', email: 'jennifer.taylor@company.com' },
  { id: 'u7', name: 'David Anderson', email: 'david.anderson@company.com' },
  { id: 'u8', name: 'Lisa Martinez', email: 'lisa.martinez@company.com' },
  { id: 'u9', name: 'James Thomas', email: 'james.thomas@company.com' },
  { id: 'u10', name: 'Amanda Garcia', email: 'amanda.garcia@company.com' },
];

// ============================================================================
// Mock Roles for Recipient Selection
// ============================================================================

export const mockRoles: MockRole[] = [
  { id: 'r1', name: 'Administrator', userCount: 5 },
  { id: 'r2', name: 'Manager', userCount: 15 },
  { id: 'r3', name: 'Editor', userCount: 25 },
  { id: 'r4', name: 'Viewer', userCount: 100 },
  { id: 'r5', name: 'External User', userCount: 50 },
];

// ============================================================================
// Mock Templates for Campaign Creation
// ============================================================================

export const mockCampaignTemplates: MockTemplate[] = [
  { id: 't1', name: 'Welcome Email', subject: 'Welcome to AebDMS!' },
  { id: 't2', name: 'Newsletter Template', subject: 'Monthly Newsletter - {{month}}' },
  { id: 't3', name: 'System Alert', subject: 'Important System Notification' },
  { id: 't4', name: 'Product Update', subject: 'New Features Available!' },
  { id: 't5', name: 'Password Reset', subject: 'Reset Your Password' },
];

// ============================================================================
// Helper to generate dates
// ============================================================================

function daysAgo(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
}

function hoursAgo(hours: number): string {
  const date = new Date();
  date.setHours(date.getHours() - hours);
  return date.toISOString();
}

function daysFromNow(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
}

// ============================================================================
// 25+ Mock Email Campaigns
// ============================================================================

export const mockEmailCampaigns: EmailCampaign[] = [
  // COMPLETED campaigns
  {
    id: 'camp-1',
    name: 'January Newsletter',
    subject: 'Your January 2026 Newsletter',
    bodyHtml: '<h1>January Newsletter</h1><p>Welcome to our monthly update...</p>',
    status: 'COMPLETED',
    type: 'NEWSLETTER',
    targetType: 'SYSTEM_USERS',
    targetRoleIds: ['r2', 'r3', 'r4'],
    totalRecipients: 140,
    sentCount: 138,
    openedCount: 89,
    clickedCount: 34,
    failedCount: 2,
    scheduledAt: daysAgo(15),
    sentAt: daysAgo(15),
    createdAt: daysAgo(20),
    updatedAt: daysAgo(15),
    createdBy: 'Marketing Team',
  },
  {
    id: 'camp-2',
    name: 'Product Launch Announcement',
    subject: 'Introducing DMS 2.0 - New Features!',
    bodyHtml: '<h1>DMS 2.0 is Here!</h1><p>We are excited to announce...</p>',
    status: 'COMPLETED',
    type: 'ANNOUNCEMENT',
    targetType: 'MIXED',
    targetRoleIds: ['r1', 'r2', 'r3'],
    externalEmails: ['partners@external.com', 'press@media.com'],
    totalRecipients: 250,
    sentCount: 248,
    openedCount: 195,
    clickedCount: 87,
    failedCount: 2,
    scheduledAt: daysAgo(10),
    sentAt: daysAgo(10),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(10),
    createdBy: 'Product Team',
  },
  {
    id: 'camp-3',
    name: 'Holiday Greetings 2025',
    subject: 'Happy Holidays from AebDMS!',
    bodyHtml: '<h1>Season\'s Greetings!</h1><p>Wishing you a wonderful holiday season...</p>',
    status: 'COMPLETED',
    type: 'NEWSLETTER',
    targetType: 'SYSTEM_USERS',
    targetRoleIds: ['r1', 'r2', 'r3', 'r4', 'r5'],
    totalRecipients: 195,
    sentCount: 195,
    openedCount: 167,
    clickedCount: 45,
    failedCount: 0,
    scheduledAt: daysAgo(45),
    sentAt: daysAgo(45),
    createdAt: daysAgo(50),
    updatedAt: daysAgo(45),
    createdBy: 'Admin User',
  },
  {
    id: 'camp-4',
    name: 'Security Update Notice',
    subject: 'Important Security Update - Action Required',
    bodyHtml: '<h1>Security Update</h1><p>We have implemented new security measures...</p>',
    status: 'COMPLETED',
    type: 'SYSTEM',
    targetType: 'SYSTEM_USERS',
    targetRoleIds: ['r1', 'r2', 'r3', 'r4'],
    totalRecipients: 145,
    sentCount: 145,
    openedCount: 132,
    clickedCount: 98,
    failedCount: 0,
    scheduledAt: daysAgo(7),
    sentAt: daysAgo(7),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(7),
    createdBy: 'Security Team',
  },
  {
    id: 'camp-5',
    name: 'Q4 Training Reminder',
    subject: 'Complete Your Q4 Training',
    bodyHtml: '<h1>Training Reminder</h1><p>Please complete your quarterly training...</p>',
    status: 'COMPLETED',
    type: 'AUTOMATED',
    targetType: 'SYSTEM_USERS',
    targetRoleIds: ['r2', 'r3'],
    totalRecipients: 40,
    sentCount: 40,
    openedCount: 38,
    clickedCount: 35,
    failedCount: 0,
    scheduledAt: daysAgo(30),
    sentAt: daysAgo(30),
    createdAt: daysAgo(35),
    updatedAt: daysAgo(30),
    createdBy: 'HR System',
  },

  // RUNNING / SENDING campaigns
  {
    id: 'camp-6',
    name: 'February Newsletter',
    subject: 'Your February 2026 Newsletter',
    bodyHtml: '<h1>February Newsletter</h1><p>This month in AebDMS...</p>',
    status: 'SENDING',
    type: 'NEWSLETTER',
    targetType: 'SYSTEM_USERS',
    targetRoleIds: ['r2', 'r3', 'r4'],
    totalRecipients: 140,
    sentCount: 87,
    openedCount: 23,
    clickedCount: 5,
    failedCount: 1,
    scheduledAt: hoursAgo(2),
    sentAt: hoursAgo(2),
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(1),
    createdBy: 'Marketing Team',
  },
  {
    id: 'camp-7',
    name: 'System Onboarding Sequence',
    subject: 'Getting Started with AebDMS',
    bodyHtml: '<h1>Welcome Aboard!</h1><p>Let us help you get started...</p>',
    status: 'RUNNING',
    type: 'AUTOMATED',
    targetType: 'SYSTEM_USERS',
    targetUserIds: ['u1', 'u2', 'u3', 'u4', 'u5'],
    totalRecipients: 5,
    sentCount: 3,
    openedCount: 2,
    clickedCount: 1,
    failedCount: 0,
    createdAt: daysAgo(5),
    updatedAt: hoursAgo(3),
    createdBy: 'Onboarding System',
  },

  // SCHEDULED campaigns
  {
    id: 'camp-8',
    name: 'Valentine\'s Day Special',
    subject: 'Special Offer for You! ❤️',
    bodyHtml: '<h1>Valentine\'s Special</h1><p>Celebrate with exclusive features...</p>',
    status: 'SCHEDULED',
    type: 'NEWSLETTER',
    targetType: 'MIXED',
    targetRoleIds: ['r2', 'r3', 'r4'],
    externalEmails: ['subscriber1@gmail.com', 'subscriber2@yahoo.com'],
    totalRecipients: 142,
    sentCount: 0,
    openedCount: 0,
    clickedCount: 0,
    failedCount: 0,
    scheduledAt: daysFromNow(7),
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
    createdBy: 'Marketing Team',
  },
  {
    id: 'camp-9',
    name: 'Maintenance Window Notice',
    subject: 'Scheduled Maintenance - Feb 15th',
    bodyHtml: '<h1>Maintenance Notice</h1><p>System will be unavailable...</p>',
    status: 'SCHEDULED',
    type: 'SYSTEM',
    targetType: 'SYSTEM_USERS',
    targetRoleIds: ['r1', 'r2', 'r3', 'r4', 'r5'],
    totalRecipients: 195,
    sentCount: 0,
    openedCount: 0,
    clickedCount: 0,
    failedCount: 0,
    scheduledAt: daysFromNow(3),
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(5),
    createdBy: 'IT Operations',
  },
  {
    id: 'camp-10',
    name: 'March Newsletter Preview',
    subject: 'March 2026 Newsletter',
    bodyHtml: '<h1>March Newsletter</h1><p>Coming soon...</p>',
    status: 'SCHEDULED',
    type: 'NEWSLETTER',
    targetType: 'SYSTEM_USERS',
    targetRoleIds: ['r2', 'r3', 'r4'],
    totalRecipients: 140,
    sentCount: 0,
    openedCount: 0,
    clickedCount: 0,
    failedCount: 0,
    scheduledAt: daysFromNow(25),
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(12),
    createdBy: 'Marketing Team',
  },

  // DRAFT campaigns
  {
    id: 'camp-11',
    name: 'Spring Sale Campaign',
    subject: 'Spring Sale - Up to 50% Off!',
    bodyHtml: '<h1>Spring Sale</h1><p>Don\'t miss our biggest sale...</p>',
    status: 'DRAFT',
    type: 'ANNOUNCEMENT',
    targetType: 'EXTERNAL',
    externalEmails: ['leads@marketing.com'],
    totalRecipients: 0,
    sentCount: 0,
    openedCount: 0,
    clickedCount: 0,
    failedCount: 0,
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(6),
    createdBy: 'Sales Team',
  },
  {
    id: 'camp-12',
    name: 'New Feature Tutorial',
    subject: 'Learn About Our Latest Features',
    bodyHtml: '<h1>New Features</h1><p>Check out what\'s new...</p>',
    status: 'DRAFT',
    type: 'TRANSACTIONAL',
    targetType: 'SYSTEM_USERS',
    targetRoleIds: ['r2', 'r3'],
    totalRecipients: 0,
    sentCount: 0,
    openedCount: 0,
    clickedCount: 0,
    failedCount: 0,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
    createdBy: 'Product Team',
  },
  {
    id: 'camp-13',
    name: 'Customer Feedback Survey',
    subject: 'We Value Your Feedback',
    bodyHtml: '<h1>Share Your Thoughts</h1><p>Help us improve...</p>',
    status: 'DRAFT',
    type: 'NEWSLETTER',
    targetType: 'MIXED',
    targetRoleIds: ['r3', 'r4'],
    externalEmails: [],
    totalRecipients: 0,
    sentCount: 0,
    openedCount: 0,
    clickedCount: 0,
    failedCount: 0,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
    createdBy: 'Customer Success',
  },
  {
    id: 'camp-14',
    name: 'Partner Onboarding Guide',
    subject: 'Welcome to Our Partner Program',
    bodyHtml: '<h1>Partner Welcome</h1><p>Thank you for joining...</p>',
    status: 'DRAFT',
    type: 'AUTOMATED',
    targetType: 'EXTERNAL',
    externalEmails: [],
    totalRecipients: 0,
    sentCount: 0,
    openedCount: 0,
    clickedCount: 0,
    failedCount: 0,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(5),
    createdBy: 'Partnerships',
  },

  // PAUSED campaigns
  {
    id: 'camp-15',
    name: 'Weekly Tips Series',
    subject: 'DMS Tip of the Week',
    bodyHtml: '<h1>Weekly Tip</h1><p>This week\'s productivity tip...</p>',
    status: 'PAUSED',
    type: 'AUTOMATED',
    targetType: 'SYSTEM_USERS',
    targetRoleIds: ['r2', 'r3', 'r4'],
    totalRecipients: 140,
    sentCount: 45,
    openedCount: 38,
    clickedCount: 12,
    failedCount: 0,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
    createdBy: 'Content Team',
  },
  {
    id: 'camp-16',
    name: 'Beta Testers Updates',
    subject: 'Beta Testing Update',
    bodyHtml: '<h1>Beta Update</h1><p>Latest from beta testing...</p>',
    status: 'PAUSED',
    type: 'ANNOUNCEMENT',
    targetType: 'SYSTEM_USERS',
    targetUserIds: ['u1', 'u3', 'u5', 'u7'],
    totalRecipients: 4,
    sentCount: 2,
    openedCount: 2,
    clickedCount: 1,
    failedCount: 0,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(7),
    createdBy: 'QA Team',
  },

  // FAILED campaigns
  {
    id: 'camp-17',
    name: 'Emergency Notification Test',
    subject: 'URGENT: System Alert',
    bodyHtml: '<h1>Emergency Alert</h1><p>This is a test...</p>',
    status: 'FAILED',
    type: 'SYSTEM',
    targetType: 'SYSTEM_USERS',
    targetRoleIds: ['r1', 'r2'],
    totalRecipients: 20,
    sentCount: 5,
    openedCount: 3,
    clickedCount: 0,
    failedCount: 15,
    scheduledAt: daysAgo(3),
    sentAt: daysAgo(3),
    createdAt: daysAgo(4),
    updatedAt: daysAgo(3),
    createdBy: 'System Admin',
  },
  {
    id: 'camp-18',
    name: 'External Promo Blast',
    subject: 'Special Promotion Inside!',
    bodyHtml: '<h1>Promo</h1><p>Limited time offer...</p>',
    status: 'FAILED',
    type: 'NEWSLETTER',
    targetType: 'EXTERNAL',
    externalEmails: ['invalid@', 'broken.com', 'test@test.test'],
    totalRecipients: 3,
    sentCount: 0,
    openedCount: 0,
    clickedCount: 0,
    failedCount: 3,
    scheduledAt: daysAgo(5),
    sentAt: daysAgo(5),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
    createdBy: 'Sales Team',
  },

  // CANCELLED campaigns
  {
    id: 'camp-19',
    name: 'Cancelled Event Notification',
    subject: 'Event Update',
    bodyHtml: '<h1>Event Cancelled</h1><p>Unfortunately...</p>',
    status: 'CANCELLED',
    type: 'ANNOUNCEMENT',
    targetType: 'SYSTEM_USERS',
    targetRoleIds: ['r2', 'r3'],
    totalRecipients: 40,
    sentCount: 0,
    openedCount: 0,
    clickedCount: 0,
    failedCount: 0,
    scheduledAt: daysAgo(2),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
    createdBy: 'Events Team',
  },

  // More COMPLETED for variety
  {
    id: 'camp-20',
    name: 'Year End Summary 2025',
    subject: 'Your 2025 Year in Review',
    bodyHtml: '<h1>Year in Review</h1><p>Here\'s your activity summary...</p>',
    status: 'COMPLETED',
    type: 'AUTOMATED',
    targetType: 'SYSTEM_USERS',
    targetRoleIds: ['r1', 'r2', 'r3', 'r4'],
    totalRecipients: 145,
    sentCount: 145,
    openedCount: 120,
    clickedCount: 78,
    failedCount: 0,
    scheduledAt: daysAgo(40),
    sentAt: daysAgo(40),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(40),
    createdBy: 'Analytics System',
  },
  {
    id: 'camp-21',
    name: 'December Newsletter',
    subject: 'December 2025 Newsletter',
    bodyHtml: '<h1>December Update</h1><p>Last month\'s highlights...</p>',
    status: 'COMPLETED',
    type: 'NEWSLETTER',
    targetType: 'SYSTEM_USERS',
    targetRoleIds: ['r2', 'r3', 'r4'],
    totalRecipients: 135,
    sentCount: 133,
    openedCount: 98,
    clickedCount: 42,
    failedCount: 2,
    scheduledAt: daysAgo(38),
    sentAt: daysAgo(38),
    createdAt: daysAgo(42),
    updatedAt: daysAgo(38),
    createdBy: 'Marketing Team',
  },
  {
    id: 'camp-22',
    name: 'Account Verification',
    subject: 'Verify Your Account',
    bodyHtml: '<h1>Account Verification</h1><p>Please verify your email...</p>',
    status: 'COMPLETED',
    type: 'TRANSACTIONAL',
    targetType: 'SYSTEM_USERS',
    targetUserIds: ['u6', 'u8', 'u10'],
    totalRecipients: 3,
    sentCount: 3,
    openedCount: 3,
    clickedCount: 3,
    failedCount: 0,
    sentAt: daysAgo(12),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
    createdBy: 'Auth System',
  },
  {
    id: 'camp-23',
    name: 'Invoice Reminder Batch',
    subject: 'Invoice Payment Reminder',
    bodyHtml: '<h1>Payment Reminder</h1><p>Your invoice is due...</p>',
    status: 'COMPLETED',
    type: 'TRANSACTIONAL',
    targetType: 'EXTERNAL',
    externalEmails: ['billing@client1.com', 'accounts@client2.com', 'finance@client3.org'],
    totalRecipients: 3,
    sentCount: 3,
    openedCount: 2,
    clickedCount: 1,
    failedCount: 0,
    sentAt: daysAgo(8),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
    createdBy: 'Billing System',
  },
  {
    id: 'camp-24',
    name: 'API Deprecation Notice',
    subject: 'Important: API v1 Deprecation',
    bodyHtml: '<h1>API Update</h1><p>API v1 will be deprecated...</p>',
    status: 'COMPLETED',
    type: 'SYSTEM',
    targetType: 'MIXED',
    targetRoleIds: ['r1'],
    externalEmails: ['dev@partner1.com', 'api@partner2.com'],
    totalRecipients: 7,
    sentCount: 7,
    openedCount: 7,
    clickedCount: 5,
    failedCount: 0,
    sentAt: daysAgo(20),
    createdAt: daysAgo(22),
    updatedAt: daysAgo(20),
    createdBy: 'Dev Team',
  },
  {
    id: 'camp-25',
    name: 'Compliance Training Announcement',
    subject: 'Mandatory Compliance Training',
    bodyHtml: '<h1>Compliance Training</h1><p>All employees must complete...</p>',
    status: 'COMPLETED',
    type: 'ANNOUNCEMENT',
    targetType: 'SYSTEM_USERS',
    targetRoleIds: ['r1', 'r2', 'r3', 'r4'],
    totalRecipients: 145,
    sentCount: 145,
    openedCount: 140,
    clickedCount: 138,
    failedCount: 0,
    sentAt: daysAgo(25),
    createdAt: daysAgo(27),
    updatedAt: daysAgo(25),
    createdBy: 'Compliance Team',
  },
  {
    id: 'camp-26',
    name: 'New Office Location',
    subject: 'We\'re Moving! New Office Address',
    bodyHtml: '<h1>New Location</h1><p>We are excited to announce our new office...</p>',
    status: 'DRAFT',
    type: 'ANNOUNCEMENT',
    targetType: 'MIXED',
    targetRoleIds: ['r1', 'r2', 'r3', 'r4', 'r5'],
    externalEmails: [],
    totalRecipients: 0,
    sentCount: 0,
    openedCount: 0,
    clickedCount: 0,
    failedCount: 0,
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(2),
    createdBy: 'HR Team',
  },
];

// ============================================================================
// Mock Campaign Activities
// ============================================================================

export const mockCampaignActivities: Record<string, CampaignActivity[]> = {
  'camp-1': [
    { id: 'a1', campaignId: 'camp-1', type: 'CREATED', description: 'Campaign created', timestamp: daysAgo(20), userName: 'Marketing Team' },
    { id: 'a2', campaignId: 'camp-1', type: 'SCHEDULED', description: 'Campaign scheduled for Jan 22, 2026', timestamp: daysAgo(18), userName: 'Marketing Team' },
    { id: 'a3', campaignId: 'camp-1', type: 'STARTED', description: 'Campaign started sending', timestamp: daysAgo(15), userName: 'System' },
    { id: 'a4', campaignId: 'camp-1', type: 'COMPLETED', description: 'Campaign completed. 138/140 emails sent successfully', timestamp: daysAgo(15), userName: 'System' },
  ],
  'camp-6': [
    { id: 'a5', campaignId: 'camp-6', type: 'CREATED', description: 'Campaign created', timestamp: daysAgo(3), userName: 'Marketing Team' },
    { id: 'a6', campaignId: 'camp-6', type: 'SCHEDULED', description: 'Campaign scheduled', timestamp: daysAgo(2), userName: 'Marketing Team' },
    { id: 'a7', campaignId: 'camp-6', type: 'STARTED', description: 'Campaign started sending', timestamp: hoursAgo(2), userName: 'System' },
  ],
};

// ============================================================================
// Legacy Mock Data (for backward compatibility)
// ============================================================================

export const mockEmailTemplates: EmailTemplate[] = [
  {
    id: '1',
    name: 'Welcome Email',
    subject: 'Welcome to AebDMS',
    type: 'welcome',
    status: 'active',
    usage: 156,
    lastModified: daysAgo(5),
    createdBy: 'Admin User',
    preview: 'Welcome to our document management system...'
  },
  {
    id: '2',
    name: 'Password Reset',
    subject: 'Reset Your Password',
    type: 'password_reset',
    status: 'active',
    usage: 89,
    lastModified: daysAgo(10),
    createdBy: 'Admin User',
    preview: 'Click the link below to reset your password...'
  },
  {
    id: '3',
    name: 'Document Shared',
    subject: 'Document Shared with You',
    type: 'document_shared',
    status: 'active',
    usage: 234,
    lastModified: daysAgo(8),
    createdBy: 'Admin User',
    preview: 'A document has been shared with you...'
  },
  {
    id: '4',
    name: 'Newsletter Template',
    subject: 'Monthly Newsletter',
    type: 'newsletter',
    status: 'draft',
    usage: 0,
    lastModified: daysAgo(2),
    createdBy: 'Marketing Team',
    preview: 'Here are the latest updates and features...'
  },
  {
    id: '5',
    name: 'System Notification',
    subject: 'System Maintenance Notice',
    type: 'system_notification',
    status: 'active',
    usage: 45,
    lastModified: daysAgo(15),
    createdBy: 'System Admin',
    preview: 'We will be performing scheduled maintenance...'
  }
];

export const mockEmailLogs: EmailLog[] = [
  {
    id: '1',
    timestamp: hoursAgo(2),
    recipient: 'john.doe@company.com',
    subject: 'Welcome to AebDMS',
    campaign: 'Welcome Campaign',
    status: 'delivered',
    opened: true,
    clicked: true,
    bounceReason: null,
    deliveryTime: 1.2,
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
  },
  {
    id: '2',
    timestamp: hoursAgo(3),
    recipient: 'jane.smith@company.com',
    subject: 'Document Shared with You',
    campaign: 'Document Sharing',
    status: 'delivered',
    opened: true,
    clicked: false,
    bounceReason: null,
    deliveryTime: 0.8,
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'
  },
  {
    id: '3',
    timestamp: hoursAgo(5),
    recipient: 'invalid@email.com',
    subject: 'Password Reset',
    campaign: 'Password Reset Campaign',
    status: 'bounced',
    opened: false,
    clicked: false,
    bounceReason: 'Invalid email address',
    deliveryTime: 0,
    ipAddress: '192.168.1.102',
    userAgent: null
  },
  {
    id: '4',
    timestamp: hoursAgo(6),
    recipient: 'admin@company.com',
    subject: 'Weekly Activity Report',
    campaign: 'Weekly Reports',
    status: 'delivered',
    opened: false,
    clicked: false,
    bounceReason: null,
    deliveryTime: 2.1,
    ipAddress: '192.168.1.103',
    userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36'
  },
  {
    id: '5',
    timestamp: hoursAgo(8),
    recipient: 'user@example.com',
    subject: 'System Maintenance Notice',
    campaign: 'System Maintenance',
    status: 'failed',
    opened: false,
    clicked: false,
    bounceReason: 'SMTP connection timeout',
    deliveryTime: 0,
    ipAddress: '192.168.1.104',
    userAgent: null
  }
];

export const mockEmailStats: EmailStats = {
  totalSent: 15420,
  delivered: 14890,
  opened: 12345,
  clicked: 3456,
  bounced: 234,
  failed: 296,
  unsubscribed: 89,
  sentRate: 96.6,
  openRate: 82.9,
  clickRate: 27.9,
  clickToOpenRate: 28.0,
  bounceRate: 1.5,
  unsubscribeRate: 0.6,
  todaySent: 156,
  thisWeekSent: 1234,
  thisMonthSent: 5678,
  activeCampaigns: 3,
  scheduledCampaigns: 1,
  totalTemplates: 5
};
